---
name: Build BambuStudio

on:
  push: {}

jobs:
  linux-amd64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add debian source
        run: echo "deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe multiverse" | sudo tee /etc/apt/sources.list.d/src.list

      - name: Install dependencies
        run: |
          sudo apt-get update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y \
            git build-essential \
            autoconf pkgconf m4 \
            cmake extra-cmake-modules \
            libglu1-mesa-dev libglu1-mesa-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            eglexternalplatform-dev libglew-dev \
            libgtk-3-dev libdbus-1-dev \
            libcairo2-dev libgtk-3-dev \
            libwebkit2gtk-4.0-dev libsoup2.4-dev \
            libgstreamer1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-base1.0-dev libgstreamerd-3-dev \
            libmspack-dev libosmesa6-dev \
            libssl-dev libcurl4-openssl-dev libsecret-1-dev \
            libudev-dev curl \
            wget

      - name: Update system dependencies
        run: sudo ./BuildLinux.sh -u

      - name: Build dependencies
        run: ./BuildLinux.sh -d

      - name: Build slic3r
        run: ./BuildLinux.sh -s

      - name: Build AppImage
        run: ./BuildLinux.sh -i

      - name: Archive AppImage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: appimage
          path: |
            *.AppImage
